data:
  dataset_name: "CiteSeer"            # ['Cora', 'CiteSeer', 'PubMed', 'CS', 'Physics', 'Amazon Computers']
  samples_per_class: [5, 10, 20, 40, 60, 80]

results_path: "/home/nicolamaestri/nm_gnn/scripts/node_classification/results/CiteSeer"

model:
  hidden_channels: 128
  drop_msg: 0.9
  drop_node: 0.5
  drop_edge: 0.5
  drop_attr: 0.5
  augm: 0.1
  rew: 0.1

optimizer:
  lr: 0.01
  weight_decay: 0.0005

n_runs: 10

training:
  epochs: 500
  patience: 25
