data:
  dataset_name: "Cora"            # ['Cora', 'CiteSeer', 'PubMed', 'CS', 'Physics', 'Amazon Computers']
  samples_per_class: [5, 10]

results_path: "/home/nicolamaestri/nm_gnn/scripts/node_classification/results/Cora"

model:
  hidden_channels: 128
  drop_msg: 0.9
  DropNode: 0.5
  DropEdge: 0.5
  DropAttributes: 0.5
  augm: 0.1
  rew: 0.1

optimizer:
  lr: 0.01
  weight_decay: 0.0005

n_runs: 2

training:
  epochs: 500
  patience: 25
